version: "3.9"

volumes:
  docker_data:

services:
  mongo:
    image: mongo:6.0.3-focal
    volumes:
      - ./docker_data/db:/data/db
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
